[Server]
Address = "localhost"
Port = "8080"

[Grpc]
Address = "localhost"
Port = "50051"

[Http]
Address = "localhost"
Port = "50051"

[Logger]
File = "./calendar.log"
Level = "INFO"

[Storage]
inMemory = false
SQLHost = "localhost"
SQLPort = "5432"
SQLDbase = "calendar"
SQLUser = "calendar"
SQLPass = "12345678"