version: '3'
services:
  scheduler:
    build:
      context: ..
      dockerfile: ./cicd/scheduler/Dockerfile
    volumes:
      - ../logs:/logs
    restart: on-failure
    environment:
      APP_RABBITMQ_ADDRESS: localhost
      APP_RABBITMQ_PORT: 5672
      APP_RABBITMQ_LOGIN: rabbit
      APP_RABBITMQ_PASS: rabbit
      APP_RABBITMQ_EXCHANGE: calendar
      APP_RABBITMQ_QUEUE: notifications
      APP_RABBITMQ_KEY: events
      APP_API_ADDRESS: localhost
      APP_API_PORT: 50053
      APP_LOGGER_FILE: /logs/calendar.log
      APP_LOGGER_LEVEL: INFO
    network_mode: host
