version: '2.0'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
  calendar:
    build:
      context: ..
      dockerfile: ./cicd/calendar/Dockerfile
    ports:
      - 50051:50051
      - 50053:50053
      - 8888:8888
    volumes:
      - ../calendar.log:/calendar.log
  scheduler:
    build:
      context: ..
      dockerfile: ./cicd/scheduler/Dockerfile
    volumes:
      - ../calendar.log:/calendar.log
  sender:
    build:
      context: ..
      dockerfile: ./cicd/sender/Dockerfile
    volumes:
      - ../calendar.log:/calendar.log